### ISSUE TITLE
Wrong diagnostics in t/00-load.t

### ISSUE THREAD

**Issue by eserte** [ThePilgrim/perlcldr#12]
In Locale-CLDR-Locales-Ksh-v0.29.0's t/00-load.t I see:

```
diag( "Testing Locale::CLDR v0.29.0, Perl 5.018002, D:\strawberry\perl\bin\perl.exe" );
```

which is apparently wrong --- it probably should not be hardcoded.

**Comment by ThePilgrim** [comment]
OOps, I missed out a \ in the code that generates those tests. Thanks for catching that. Ill update it for the next release.

**Comment by ThePilgrim** [comment]
Fixed in current release
