### ISSUE TITLE
No data for language yi - Yiddish

### ISSUE THREAD

**Issue by wollmers** [ThePilgrim/perlcldr#13]
Just freshly installed:

    $ cpanm Locale::CLDR
    Locale::CLDR is up to date. (v0.29.0)

This fails:

    $ perl -e 'use Locale::CLDR;print Locale::CLDR->new("yi")->likely_script(),"\n";'
    Invalid variant at /Users/helmut/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Locale/CLDR.pm line 1284.

This works:

    $ perl -e 'use Locale::CLDR;print Locale::CLDR->new("de")->likely_script(),"\n";'
    Latin

Unicode/CLDR has it on [Languages and scripts](http://www.unicode.org/cldr/charts/29/supplemental/languages_and_scripts.html):

    Yiddish	yi		N	Hebrew	Hebr

**Comment by ThePilgrim** [comment]
Yidish should be in the next release. Not sure why it was not included in v0.29.0 however I now have an automated upload script that should ensure that all language packs are properly uploaded.
