### ISSUE TITLE
Is likely_language() not correct?

### ISSUE THREAD

**Issue by Perlover** [ThePilgrim/perlcldr#16]
Hello!

From documentation:
`likely_language()
    Given a locale with no language passed in or with the explicit language code of und, this method attempts to use the script and region data to guess the locale's language`

But quick test shows that it's not correct:

    use utf8;
    use strict;
    
    binmode STDOUT, ':utf8';
    binmode STDERR, ':utf8';
    
    use Locale::CLDR;
    
    my $locale = Locale::CLDR->new('und_FR');
    
    print $locale->likely_language, "\n", $locale->likely_script, "\n", $locale->likely_region, "\n",
	$locale->native_name, "\n", $locale->native_language, "\n";

prints:

> Unknown Language
> Latin
> France
> Unknown Language (France)
> Unknown Language

    use utf8;
    use strict;
    
    binmode STDOUT, ':utf8';
    binmode STDERR, ':utf8';
    
    use Locale::CLDR;
    
    my $locale = Locale::CLDR->new('und_Latn_FR');
    
    print $locale->likely_language, "\n", $locale->likely_script, "\n", $locale->likely_region, "\n",
	$locale->native_name, "\n", $locale->native_language, "\n";

prints:

> Unknown Language
> Latin
> France
> Unknown Language (France{0}, {1}Latin)
> Unknown Language

So even if i specify explicitly the Latin script there no guessed language...

**Comment by ThePilgrim** [comment]
That looks like a bug. I'll add a unit test and see what I can do for the next release. By the way. this project is huge so if you want to help by fixing the bug and submitting a patch or pull request I'd be very happy

**Comment by ThePilgrim** [comment]
Looking at this again getting 'Unknown Language (France{0}, {1}Latin)' is also a bug in the parsing of the native name the {0} and {1} are supposed to be replaced so they don't show.

**Comment by Perlover** [comment]
I will try to fux bug.
I think it located some there:
https://metacpan.org/source/JGNI/Locale-CLDR-v0.29.0/lib/Locale/CLDR.pm#L1353

**Comment by Perlover** [comment]
I think $likely_subtag before this string can has 'und_FR', for example and after 
`($likely_language_id, $likely_script_id, $likely_region_id) = split /_/, $likely_subtag;`
it can be with incorrect variables.
I will try to fix

**Comment by Perlover** [comment]
https://github.com/Perlover/perlcldr/commit/53993d99c1d8dcf6da78c581b11abdedc2cee957

**Comment by Perlover** [comment]
I created the Pull Request:
https://github.com/ThePilgrim/perlcldr/pull/17
