### ISSUE TITLE
CLDR v32 Released

### ISSUE THREAD

**Issue by Anonymoosed** [ThePilgrim/perlcldr#18]
2017-11-01 | CLDR v32 Released, and includes, among other things “Many fixes and small additions to certain preexisting data”.

as Locale::CLDR is at version 0.29, does this mean that CLDR data it uses is also at v29?

**Comment by ThePilgrim** [comment]
Yes.
The version number for the CPAN modules follow the following format <api version>.<cldr revision>.<release number>

As there is only me working on this and I only get to do it in my spare time releases happen in a very ad-hock manner.

**Comment by ThePilgrim** [comment]
Latest release will contain version 32 of the CLDR data
