### ISSUE TITLE
Bundle dist Europe doesn't list dependencies

### ISSUE THREAD

**Issue by ehuelsmann** [ThePilgrim/perlcldr#34]
Generating the "Europe" bundle using `mkcldr.pl` yesterday, I think there's a bug in the Bundle dists (using Europe as a showcase). The following `Build.PL` output is what I get for `Locale-CLDR/Distributions/Bundles/Europe` (please note the empty row after the "perl" dependency):

```perl
use strict;
use warnings;
use utf8;

use Module::Build;

my $builder = Module::Build->new(
    module_name         => 'Bundle::Locale::CLDR::Europe',
    license             => 'perl',
    requires        => {
        'version'                   => '0.95',
        'DateTime'                  => '0.72',
        'Moo'                       => '2',
        'MooX::ClassAttribute'      => '0.011',
		'Type::Tiny'                => 0,
        'perl'                      => '5.10.1',
        ,
    },
    dist_author         => q{John Imrie <john.imrie1@gmail.com>},
    dist_version        => '0.34.0',
    build_requires => {
        'ok'                => 0,
        'Test::Exception'   => 0,
        'Test::More'        => '0.98',
    },
    add_to_cleanup      => [ 'Bundle-Locale-CLDR-Europe-*' ],
	configure_requires => { 'Module::Build' => '0.40' },
	release_status => 'stable',
	dist_abstract => 'Locale::CLDR - Data Package (  )',
	meta_add => {
		keywords => [ qw( locale CLDR locale-data-pack ) ],
		resources => {
			homepage => 'https://github.com/ThePilgrim/perlcldr',
			bugtracker => 'https://github.com/ThePilgrim/perlcldr/issues',
			repository => 'https://github.com/ThePilgrim/perlcldr.git',
		},
	},
);

$builder->create_build_script();
```

Since the `Europe.pm` module contains a series of bundle references, I'd expect those to be listed in the "requires" section above on the empty line below the "perl" requirement:

```perl
package Bundle::Locale::CLDR::Europe;

use version;

our $VERSION = version->declare('v0.34.0');

=head1 NAME Bundle::Locale::CLDR::Europe

=head1 CONTENTS

Bundle::Locale::CLDR::Easterneurope 0.34.0
Bundle::Locale::CLDR::Westerneurope 0.34.0
Bundle::Locale::CLDR::Northerneurope 0.34.0
Bundle::Locale::CLDR::Southerneurope 0.34.0

=cut

1;
```

**Comment by ThePilgrim** [comment]
Have you tried using the version on [gitlab](https://gitlab.com/ThePilgrim1/perlcldr). I think that's more up to date.

**Comment by ehuelsmann** [comment]
No, I didn't (how should I have known about its existence? Are there references?)

I have run it now, but the result -- apart from it being numbered 0.35.0-TRIAL - is exactly the same: the Build.PL doesn't specify the listed bundles as deps...

**Comment by ehuelsmann** [comment]
And neither does the version uploaded to CPAN: https://metacpan.org/release/JGNI/Bundle-Locale-CLDR-Europe-0.34.0/source/Build.PL#17

**Comment by ThePilgrim** [comment]
OK thanks for that, I'm currently in the process of looking for a new flat so it will be a couple of months before I can get around to looking at this.

**Comment by ehuelsmann** [comment]
@ThePilgrim hi, I'd like to contribute to solve this problem, but am puzzled by the structure of the output generator. Could you maybe add some more docs in the Perl source code, or add a high level documentation elsewhere? (If it already exists, please let me know!)

**Comment by ThePilgrim** [comment]
> @ThePilgrim hi, I'd like to contribute to solve this problem, but am puzzled by the structure of the output generator. Could you maybe add some more docs in the Perl source code, or add a high level documentation elsewhere? (If it already exists, please let me know!)

There is very little documentation in that script, I'll see what I can do to remedy it.

**Comment by ehuelsmann** [comment]
Ok. After consultation with the #perl channel on libera.chat and looking at other bundles, it seems that this is expected behaviour. However, this makes `cpanm` unsuitable for installing dependencies specified in bundles.

**Comment by ehuelsmann** [comment]
Closing and heading over to cpanm to report this as an issue there.

**Comment by ehuelsmann** [comment]
Even more `cpanm --scandeps Bundle::DBI` seems to add the implied dependencies.
