### ISSUE TITLE
Locale::CLDR::Locales::* modules load `bignum`, breaking every project which sets `$Math::BigFloat::downgrade` or `$Math::BigInt::upgrade`

### ISSUE THREAD

**Issue by ehuelsmann** [ThePilgrim/perlcldr#39]
As discussed in pjacklam/p5-Math-BigInt#11 and also reported in #36, with recent improvements in down- and upgrading in Math::BigInt/Math::BigFloat (released as part of Perl 5.36+), there are now more operations which correctly return the upgraded/downgraded result. However, this also makes it more visible that this project is overriding the up- and downgrade selections of the projects it's embedded in.

What's more: it overrides the selection in the project it's part of, not right from the start, but only once the first `Locale::CLDR::Locales::*` module is loaded (which happens dynamically). This behaviour makes the type failures, e.g. in [`LedgerSMB`](/ledgersmb/LedgerSMB) seem random.

Why does this module use `bignum` itself? why doesn't it advise users to do that *or* failing that, take other measures?

**Comment by ThePilgrim** [comment]
I think bigfloat will work I'm going to make a trial version for 0.34.2 and see what happens

**Comment by ehuelsmann** [comment]
Thanks! That would be hugely appreciated. Since I have some code which is reliably failing, I'll reverse the mitigating measures and see if the code remains stable with the new release and without the measures.

**Comment by ThePilgrim** [comment]
You may have noticed a lack of development over the last year, this is a massive project and most of it is written by me. I needed a brake.  😀

**Comment by ehuelsmann** [comment]
Yes. I have. Don't feel pressured. I know how it is; we're using the project in LedgerSMB (https://ledgersmb.org) which is no small effort either (we've been modernizing the code base for more than 15 years now and still not done).

**Comment by ThePilgrim** [comment]
I'm still uploading to CPAN, have to throttle uploads or I get a slap on the wrist but there's sufficient up there to test with US and British English Look for Locale-CLDR-v0.34.2-TRIAL1 and then *-v0.34.2-TRIAL1for the language packs.
Can you let me know if it works 😀

**Comment by ehuelsmann** [comment]
> Can you let me know if it works 😀
> Upload is fully complete

In a docker image where this is currently broken:

```bash
docker exec -ti --user root <container name> bash
# cpanm --reinstall --notest https://cpan.metacpan.org/authors/id/J/JG/JGNI/Locale-CLDR-v0.34.2-TRIAL1.tar.gz
# cpanm --reinstall --notest https://cpan.metacpan.org/authors/id/S/ST/STRANGE/Locale-CLDR-Locales-En-v0.34.1.tar.gz
```

And restarting the docker container.

:tada: yes! It works again now! No workarounds necessary anymore to restore the value of `$Math::BigFloat::downgrade`.

**Comment by ehuelsmann** [comment]
Thank you for the quick response!

**Comment by ThePilgrim** [comment]
I'm getting a none development version generated, once that's done I'll upload it to CPAN. With any luck it will be uploaded by the end of today
