### ISSUE TITLE
Deep recursion when creating objects for specific regions

### ISSUE THREAD

**Issue by bschmalhofer** [ThePilgrim/perlcldr#41]
I added translation of country names to a web application using Locale::CLDR. Testing with BV, Bouvet Island, caused high processor load on the  web server. 

This can be reproduced with a simple script. 
```
$ perl bouvet.pl 
Deep recursion on subroutine "Locale::CLDR::new" at /usr/local/share/perl/5.34.0/Locale/CLDR.pm line 1456.
Deep recursion on subroutine "Locale::CLDR::BUILD" at (eval 444) line 1520.
Deep recursion on anonymous subroutine at (eval 425) line 16.
```

The debugger shows that the recursion occurs when the likely subtags are determined. I suppose that an infinite loop is entered because of some specific likely subtags.
```
$ grep -r "=> 'und_" local/lib/perl5/Locale/CLDR/LikelySubtags.pm 
		'und_AQ'	=> 'und_Latn_AQ',
		'und_BV'	=> 'und_Latn_BV',
		'und_CP'	=> 'und_Latn_CP',
		'und_GS'	=> 'und_Latn_GS',
		'und_HM'	=> 'und_Latn_HM',
```
The regions AQ, BV, CP, GS, and HM all show the deep recursion.

[bouvet.pl.txt](https://github.com/ThePilgrim/perlcldr/files/13531947/bouvet.pl.txt)

**Comment by ThePilgrim** [comment]
Thank you for your bug report, I hadn't considered recursion with likely subtags. I'll take a look as soon as I can.

**Comment by ThePilgrim** [comment]
I'm generating a development version of 0.34.4
I'll add a note here once it's uploaded to CPAN

**Comment by bschmalhofer** [comment]
Thanks @ThePilgrim , I will test https://metacpan.org/release/JGNI/Locale-CLDR-v0.34.4-TRIAL1 on the weekend.

**Comment by bschmalhofer** [comment]
Hi @ThePilgrim,

I tested the web app with Locale::CLDR 0.34.4 and the translation of country names worked fine. Thanks for fixing this bug!
