### ISSUE TITLE
Translations for North Macedonia and Eswatini

### ISSUE THREAD

**Issue by bschmalhofer** [ThePilgrim/perlcldr#42]
I noticed that in Locale::CLDR  0.34.4 the translations for MK and SZ still were based on the old names Macedonia and Swaziland. These countries were renamed to North Macedonia and Eswatini.  It looks like the name changes have been included in CLDR 35.
http://blog.unicode.org/2019/03/unicode-cldr-version-35-languagelocale.html .

The current version of Unicode CLDR is 0.44.1.  I suggest that a new release of Locale::CLDR based on the current version should be made.

**Comment by ThePilgrim** [comment]
I'm working on a release for version 40 of CLDR. If I can get that to work I'll move onto the latest CLDR version

**Comment by ThePilgrim** [comment]
Upload of v0.40.0 complete. I will start working on v0.44.0 now

**Comment by bschmalhofer** [comment]
Thanks.
I have updated the required version of Locale::CLDR to 0.40.0.   Now I see, for German, in the OTOBO country selection the country names "Nordmazedonien" and "Eswatini".

**Comment by ThePilgrim** [comment]
I can close this now?

**Comment by bschmalhofer** [comment]
Yes, the issue can be closed. Thanks again for working on this.

For OTOBO, the next step, in my little side project, will be using the translation of language names from Locale::CLDR.
