### ISSUE TITLE
get_installed_locales() returns empty list

### ISSUE THREAD

**Issue by bschmalhofer** [ThePilgrim/perlcldr#44]
Hi,

I have been trying to use Locale::CLDR for getting translated language names. This works fine when the language pack is installed. When a language pack is not installed I'm getting the English language name. For distinguishing between the two cases it tried to call `installed_locales()`. However, in my case I'm getting an empty list, even if I have language packs installed.

The reason seems to be that I have installed Locale::CLDR and the language packs with `local::lib`. So the check in _CLDR,pm_ is always false. See
https://github.com/ThePilgrim/perlcldr/blob/76f91a8cd0ce74383720794a2f572840203b4082/Locale-CLDR/lib/Locale/CLDR.pm#L786

My installation looks like:

```
otobo@c480dcdf5152:~$ perldoc -l Locale::CLDR
/opt/otobo_install/local/lib/perl5/Locale/CLDR.pm
otobo@c480dcdf5152:~$ ls /opt/otobo_install/local/lib/perl5/Locale/CLDR/Locales/
Ar  Ar.pm  De  De.pm  En  En.pm  Es  Es.pm  Hu  Hu.pm  Ko  Ko.pm  Nb  Nb.pm  No.pm  Pt  Pt.pm  Root.pm  Ru  Ru.pm  Sr  Sr.pm  Zh  Zh.pm

```
Note that the dir _Locales_ is in _perl5_, not in _lib_.

**Comment by ThePilgrim** [comment]
Hi,

> I have been trying to use Locale::CLDR for getting translated language names. This works fine when the language pack is installed. When a language pack is not installed I'm getting the English language name. 

This is the expected behavior, if you need the language name translated you need to install the correct language pack.

> The reason seems to be that I have installed Locale::CLDR and the language packs with `local::lib`. So the check in _CLDR,pm_ is always false. 

The code expects the Locale data to be under lib/Locale/CLDR/Locales I'll change the regex to _m#/lib/.*Locale/CLDR/Locales#_ which should fix the problem with local::lib

**Comment by bschmalhofer** [comment]
Hi John,

thanks for the quick fix. 

I tested Locale::CLDR 0.44.0-TRIAL5 with
`cpanm  -l local https://cpan.metacpan.org/authors/id/J/JG/JGNI/Locale-CLDR-v0.44.0-TRIAL5.tar.gz` in my devel Docker container. Calling `perl -MLocale::CLDR -MData::Dx -E 'my $l = Locale::CLDR->new; Dx $l->installed_locales'` then gave the list of the installed locales. Looks good, the issue can be closed from my side.

For my code I switched to tentatively loading the relevant language pack. This is because I have Locale::CLDR and some selected language packs installed in one location. Additionally added language packs would be added in another location and likely not be picked up by `installed_locales()`.

**Comment by ThePilgrim** [comment]
If you have the language packs in different locations then there's not much I can do, I suppose I could scan every directory in _@INC_, but that seams a bit excessive for what seams like an edge case. If you want that code could you raise it as a separate issue and I'll close this one.

Thanks,

John
