### ISSUE TITLE
Minimum perl version 5.14 for Locale::CLDR 0.44.0

### ISSUE THREAD

**Issue by jddurand** [ThePilgrim/perlcldr#46]
Locale::CLDR version 0.44.0 uses the non-destructive substitution "r" modifier, requiring perl minimum version 5.14 if we trust https://www.perl.com/pub/2011/05/new-features-of-perl-514-non-destructive-substitution.html/ .

C.f. https://www.cpantesters.org/cpan/report/e376ad6c-d539-11ee-a9cd-8673b46fd3dd

that contains:

`Error:  syntax error at /export/home/jddurand/.cpan/build/Locale-CLDR-v0.44.0-jbpkwP/blib/lib/Locale/CLDR.pm line 1630, near "s/^[uU][-_]//r"`

**Comment by ThePilgrim** [comment]
Fixed in version 5.44.1
