### ISSUE TITLE
Can't find Unicode property definition "Block=CJK_Unified_Ideograph" in regex

### ISSUE THREAD

**Issue by eserte** [ThePilgrim/perlcldr#7]
Locale::CLDR does not compile anymore with perl 5.23.4. The error is: `Can't find Unicode property definition "Block=CJK_Unified_Ideograph" in regex`

Sample cpantesters report: http://www.cpantesters.org/cpan/report/e9ac4ed2-7e10-11e5-b3a0-9c9ddfbfc7aa

**Comment by ThePilgrim** [comment]
Incorrect name in Property it should be Block=CJK_Unified_Ideographs 
This has been picked up by Perl 5.23.4 as it is stricter about the names of Properties and checks them at compile time

Fixed in Locale::CLDR version 0.28.2
