### ISSUE TITLE
certain locale strings have broken single quoting

### ISSUE THREAD

**Issue by jhi** [ThePilgrim/perlcldr#8]
First off: I'm using 0.25.4 in an old dusty distribution, cannot trivially see whether the newest version addresses these cases.  But just in case:

Locale/CLDR/Ha.pm
Locale/CLDR/Mgh.pm
Locale/CLDR/Teo.pm

Ha.pm has the issue in its 'nostr':

        default         => sub { qr'^(?i:a'a|a|no|n)$' }

Mgh.pm has the issue in its 'nostr':

        default         => sub { qr'^(?i:akin'tuna|a|no|n)$' }

Teo.pm has the issue in its 'calendar_months':

                                                        'Omodok\'king'ol',

The first two look like a problem of not using e.g. {} as the qr delimiters; the third one looks like a problem with a missing 'g' in a s{}{}?  (just guessing)

**Comment by ThePilgrim** [comment]
Thanks for the report, you are the first confirmed user of the code :-) 
I'll see if I can get a fix out on CPAN in the next 24 hours for the 0.25.x tree

**Comment by jhi** [comment]
I'm strictly speaking not "using" the code, I was trying just PPI on everything that was installed on a system...

**Comment by ThePilgrim** [comment]
OK, well thanks for the report. That bug is present in the current code base so needed looking at

**Comment by ThePilgrim** [comment]
Fixed in version 0.28.3
